runtime: python39
api_version: 1
instance_class: F1
service: service-name
env: flex

inbound_services:
  - warmup

env_variables:
  ENV_VARIABLE: 'value'

handlers:
  - url: /
    script: home.app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  max_concurrent_requests: 50

basic_scaling:
  max_instances: 11
  idle_timeout: 10m

manual_scaling:
  instances: 5
