apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-rest-api
  name: k8s-rest-api
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-rest-api
  sessionAffinity: None
  type: LoadBalancer
